import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.*;
import java.util.Scanner;

/**
 * Shinn Edit text editing GUI
 * @author Patrick Shinn
 * @version 5/9/16
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        loadFile();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("text files", "txt", "text");
        FileNameExtensionFilter filter1 = new FileNameExtensionFilter("java files", "java");
        saveWarning.setLocationRelativeTo(this);
        chooser.setFileFilter(filter);
        chooser.setFileFilter(filter1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // builds the GUI components.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth()/2;
        double height = screenSize.getHeight()/2;
        saveWarning = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        bntDontSave = new javax.swing.JButton();
        themeFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        rdrLight = new javax.swing.JRadioButton();
        rdrDark = new javax.swing.JRadioButton();
        btnSaveTheme = new javax.swing.JButton();
        aboutFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        comboFonts = new javax.swing.JComboBox<>();
        lblFonts = new javax.swing.JLabel();
        comboPoint = new javax.swing.JComboBox<>();
        lblPt = new javax.swing.JLabel();
        seperator = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenuItem();
        fileOpen = new javax.swing.JMenuItem();
        fileSave = new javax.swing.JMenuItem();
        fileSaveAs = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        editTheme = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        saveWarning.setLocation((int)(width - 266), (int)(height - 68.5));
        saveWarning.setTitle("File Not Saved");
        saveWarning.setMinimumSize(new java.awt.Dimension(532, 137));
        saveWarning.setResizable(false);

        jLabel1.setText("You are about to close without saving, would you like to save?");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        bntDontSave.setText("Don't Save");
        bntDontSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDontSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(bntDontSave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(bntDontSave))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout saveWarningLayout = new javax.swing.GroupLayout(saveWarning.getContentPane());
        saveWarning.getContentPane().setLayout(saveWarningLayout);
        saveWarningLayout.setHorizontalGroup(
            saveWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        saveWarningLayout.setVerticalGroup(
            saveWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveWarningLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        themeFrame.setTitle("Themes");
        themeFrame.setMinimumSize(new java.awt.Dimension(400, 150));
        themeFrame.setResizable(false);
        themeFrame.setSize(new java.awt.Dimension(400, 150));

        jPanel3.setMaximumSize(new java.awt.Dimension(100, 100));

        rdrLight.setText("Light");
        rdrLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdrLightActionPerformed(evt);
            }
        });

        rdrDark.setText("Dark");
        rdrDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdrDarkActionPerformed(evt);
            }
        });

        btnSaveTheme.setText("Save");
        btnSaveTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(rdrLight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(rdrDark)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdrLight)
                    .addComponent(rdrDark))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveTheme)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout themeFrameLayout = new javax.swing.GroupLayout(themeFrame.getContentPane());
        themeFrame.getContentPane().setLayout(themeFrameLayout);
        themeFrameLayout.setHorizontalGroup(
            themeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        themeFrameLayout.setVerticalGroup(
            themeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        aboutFrame.setTitle("About");
        aboutFrame.setMinimumSize(new java.awt.Dimension(395, 100));
        aboutFrame.setSize(new java.awt.Dimension(395, 100));

        jLabel2.setText("Shinn Edit");

        jLabel3.setText("Version: 1.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout aboutFrameLayout = new javax.swing.GroupLayout(aboutFrame.getContentPane());
        aboutFrame.getContentPane().setLayout(aboutFrameLayout);
        aboutFrameLayout.setHorizontalGroup(
            aboutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutFrameLayout.setVerticalGroup(
            aboutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shinn Edit");

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAreaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        comboFonts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Times New Roman", "Arial", "Sans", "Ubuntu" }));
        comboFonts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFontsActionPerformed(evt);
            }
        });

        lblFonts.setText("Fonts");

        comboPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20" }));
        comboPoint.setMaximumSize(new java.awt.Dimension(95, 25));
        comboPoint.setMinimumSize(new java.awt.Dimension(95, 25));
        comboPoint.setPreferredSize(new java.awt.Dimension(95, 25));
        comboPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPointActionPerformed(evt);
            }
        });

        lblPt.setText("Point");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(comboFonts, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFonts, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(seperator, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboFonts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFonts)
                            .addComponent(comboPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setBorder(null);
        menuBar.setEnabled(false);
        menuBar.setMaximumSize(new java.awt.Dimension(37, 32769));
        menuBar.setMinimumSize(new java.awt.Dimension(37, 2));
        menuBar.setName(""); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(37, 21));

        menuFile.setText("File");

        menuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuClose.setText("Close");
        menuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseActionPerformed(evt);
            }
        });
        menuFile.add(menuClose);

        fileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fileOpen.setText("Open");
        fileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenActionPerformed(evt);
            }
        });
        menuFile.add(fileOpen);

        fileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fileSave.setText("Save");
        fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveActionPerformed(evt);
            }
        });
        menuFile.add(fileSave);

        fileSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fileSaveAs.setText("Save As");
        fileSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(fileSaveAs);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");

        editTheme.setText("Theme");
        editTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editThemeActionPerformed(evt);
            }
        });
        menuEdit.add(editTheme);

        menuBar.add(menuEdit);

        menuHelp.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuHelp.add(jMenuItem1);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(923, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // usage variables
    private String[] settings = new String[3];
    private final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private final double width = screenSize.getWidth()/2;
    private final double height = screenSize.getHeight()/2;
    private File selectedFile;
    private Boolean fileOpened = false;
    private final JFileChooser chooser = new JFileChooser();
    private String oldLine = "";
    
    // icon
    ImageIcon image = new ImageIcon("icon.png");
    // fonts
    private final Font timesNewRoman = new Font("Times New Roman", Font.PLAIN, 12);
    private final Font arial = new Font("Arial", Font.PLAIN, 12);
    private final Font sans = new Font("Sans", Font.PLAIN, 12);
    private final Font ubuntu = new Font("Ubuntu", Font.PLAIN, 12);



    // Opens a file of the user's choice for editing.
    private void fileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenActionPerformed
        FileReader myReader;
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = chooser.getSelectedFile();
            try{
                myReader = new FileReader(selectedFile);
                Scanner scan = new Scanner(myReader);
                String text = "";
                while (scan.hasNextLine()){
                    String line = scan.nextLine();
                    text += line + "\n";
                }
                textArea.setText(text);
                System.out.println("Selected file: " + selectedFile.getAbsolutePath());
                fileOpened = true;
            }catch (IOException error){
                // do nothing
            }

        }
    }//GEN-LAST:event_fileOpenActionPerformed

    /*
    Saves the text file. If the file has not been saved before, a new save file is generated, otherwise it is saved
    to the previous file that was saved to.
     */
    private void fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveActionPerformed
        String line = textArea.getText();
        if (!fileOpened){
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
                File fileToSave = chooser.getSelectedFile();
                try{
                    PrintWriter saveFile = new PrintWriter(fileToSave);
                    saveFile.print(line);
                    saveFile.close();
                    selectedFile = fileToSave;
                    fileOpened = true;
                    oldLine = line;
                }catch (IOException error){
                    // do nothing
                }
            }
        }else{
            try {
                PrintWriter writer = new PrintWriter(selectedFile);
                writer.print(line);
                writer.close();
                oldLine = line;
            }catch (IOException error){
                // do nothing
            }
        }

    }//GEN-LAST:event_fileSaveActionPerformed

    // Save file under a new name, save as
    private void fileSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveAsActionPerformed
        String line = textArea.getText();
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
                File fileToSave = chooser.getSelectedFile();
                try{
                    PrintWriter saveFile = new PrintWriter(fileToSave);
                    saveFile.print(line);
                    saveFile.close();
                    selectedFile = fileToSave;
                    fileOpened = true;
                    oldLine = line;
                }catch (IOException error){
                    // do nothing
                }
            }
    }//GEN-LAST:event_fileSaveAsActionPerformed

    // Closes the current file, if not saved, it will ask the user if they want to save their work
    private void menuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseActionPerformed
        if (!oldLine.equals(textArea.getText())){
            saveWarning.setVisible(true);
        }else {
            fileOpened = false;
            textArea.setText("");
        }
    }//GEN-LAST:event_menuCloseActionPerformed

    // Saves the users work in a file not saved warning.
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String line = textArea.getText();
        if (!fileOpened){
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
                File fileToSave = chooser.getSelectedFile();
                try{
                    PrintWriter saveFile = new PrintWriter(fileToSave);
                    saveFile.print(line);
                    saveFile.close();
                    selectedFile = fileToSave;
                    fileOpened = true;
                    oldLine = line;
                }catch (IOException error){
                    // do nothing
                }
            }
        }else{
            try {
                PrintWriter writer = new PrintWriter(selectedFile);
                writer.print(line);
                writer.close();
                oldLine = line;
            }catch (IOException error){
                // do nothing
            }
        }
        saveWarning.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    // Does not save the users work in a file not saved warning.
    private void bntDontSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDontSaveActionPerformed
        fileOpened = false;
        textArea.setText("");
        saveWarning.setVisible(false);
    }//GEN-LAST:event_bntDontSaveActionPerformed

    // Selects light theme.
    private void rdrLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdrLightActionPerformed
        rdrDark.setSelected(false);
    }//GEN-LAST:event_rdrLightActionPerformed

    // Selects dark theme.
    private void rdrDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdrDarkActionPerformed
        rdrLight.setSelected(false);
    }//GEN-LAST:event_rdrDarkActionPerformed

    // Applies user theme selection choice.
    private void btnSaveThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveThemeActionPerformed
        if (rdrLight.isSelected()) {
            textArea.setBackground(Color.WHITE);
            textArea.setForeground(Color.BLACK);
            settings[0] = "Light";
        }
        else if (rdrDark.isSelected()) {
            textArea.setBackground(Color.DARK_GRAY);
            textArea.setForeground(Color.WHITE);
            settings[0] = "Dark";
        }

        themeFrame.setVisible(false);
    }//GEN-LAST:event_btnSaveThemeActionPerformed

    // Shows the about frame.
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        aboutFrame.setLocation((int)(width - aboutFrame.getWidth()/2),(int)(height - aboutFrame.getHeight()/2));
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Shows the edit theme frame.
    private void editThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editThemeActionPerformed
        themeFrame.setLocation((int)(width - themeFrame.getWidth()/2),(int)(height - themeFrame.getHeight()/2));
        themeFrame.setVisible(true);
    }//GEN-LAST:event_editThemeActionPerformed

    // Allows the user to select a font from a list and apply it.
    private void comboFontsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFontsActionPerformed
        switch (comboFonts.getSelectedIndex()){
            case 0:
                textArea.setFont(timesNewRoman);
                break;
            case 1:
                textArea.setFont(arial);
                break;
            case 2:
                textArea.setFont(sans);
                break;
            case 3:
                textArea.setFont(ubuntu);
                break;

        }

        Font font = textArea.getFont();
        lblFonts.setText(font.getName());
       switch (comboPoint.getSelectedIndex()){
           case 0:
               textArea.setFont(font.deriveFont(12f));
               break;
           case 1:
               textArea.setFont(font.deriveFont(14f));
               break;
           case 2:
               textArea.setFont(font.deriveFont(16f));
               break;
           case 3:
               textArea.setFont(font.deriveFont(18f));
               break;
           case 4:
               textArea.setFont(font.deriveFont(20f));
               break;
       }
    }//GEN-LAST:event_comboFontsActionPerformed

    // Allows the user to select a font size from a list, them applies it.
    private void comboPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPointActionPerformed
        Font font = textArea.getFont();
        switch (comboPoint.getSelectedIndex()) {
            case 0:
                textArea.setFont(font.deriveFont(12f));
                break;
            case 1:
                textArea.setFont(font.deriveFont(14f));
                break;
            case 2:
                textArea.setFont(font.deriveFont(16f));
                break;
            case 3:
                textArea.setFont(font.deriveFont(18f));
                break;
            case 4:
                textArea.setFont(font.deriveFont(20f));
                break;

        }
    }//GEN-LAST:event_comboPointActionPerformed

    // Keyboard shortcuts
    private void textAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyPressed

    }//GEN-LAST:event_textAreaKeyPressed

    // loads the setting file if it exists, then applies the settings.
    private void loadFile() { // loads saved settings
        try{
            FileInputStream fis = new FileInputStream("settings.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            settings = (String[]) ois.readObject();
            ois.close();
            fis.close();

        }catch (IOException error){
            settings[0] = "Light";
            settings[1] = "Times New Roman";
            settings[2] = "12";
        }catch (ClassNotFoundException error){
            settings[0] = "Light";
            settings[1] = "Times New Roman";
            settings[2] = "12";
        }
        switch (settings[0]){
            case "Light":
                rdrLight.setSelected(true);
                textArea.setBackground(Color.WHITE);
                textArea.setForeground(Color.BLACK);
                break;
            case "Dark":
                rdrDark.setSelected(true);
                textArea.setBackground(Color.DARK_GRAY);
                textArea.setForeground(Color.WHITE);
                break;
        }
        switch (settings[1]){
            case "Times New Roman":
                comboFonts.setSelectedIndex(0);
                break;
            case "Arial":
                comboFonts.setSelectedIndex(1);
                break;
            case "Sans":
                comboFonts.setSelectedIndex(2);
                break;
            case "Ubuntu":
                comboFonts.setSelectedIndex(3);
                break;
        }
        switch (settings[2]){
            case "12":
                comboPoint.setSelectedIndex(0);
                break;
            case "14":
                comboPoint.setSelectedIndex(1);
                break;
            case "16":
                comboPoint.setSelectedIndex(2);
                break;
            case "18":
                comboPoint.setSelectedIndex(3);
                break;
            case "20":
                comboPoint.setSelectedIndex(4);
                break;
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame aboutFrame;
    private javax.swing.JButton bntDontSave;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveTheme;
    private javax.swing.JComboBox<String> comboFonts;
    private javax.swing.JComboBox<String> comboPoint;
    private javax.swing.JMenuItem editTheme;
    private javax.swing.JMenuItem fileOpen;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JMenuItem fileSaveAs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFonts;
    private javax.swing.JLabel lblPt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JRadioButton rdrDark;
    private javax.swing.JRadioButton rdrLight;
    private javax.swing.JDialog saveWarning;
    private javax.swing.JSeparator seperator;
    private javax.swing.JTextArea textArea;
    private javax.swing.JFrame themeFrame;
    // End of variables declaration//GEN-END:variables
}
